### ISSUE TITLE
Current release is not listed as compatible with latest FixedPointNumbers

### ISSUE THREAD

**Issue by ssfrr** [Keno/VT100.jl#17]
The currently-tagged version has an upper-bound on FixedPointNumbers at 0.5.x, but the latest version is 0.6.1. I'm not sure if the right approach is to tag a new release of VT100 at current master, or just update the compatibilty listing in General for the current release (assuming that it is actually compatible of course)

This is causing a conflict with Plots.jl, which requres FixedPointNumbers at 0.6.x.

**Comment by KristofferC** [comment]
This is fixed.
